language: cpp
dist: bionic
compiler:
- gcc
addons:
  apt:
    update: true
    packages:
       - g++-8
       - libsdl2-dev
       - libsdl2-image-dev
       - libsdl2-mixer-dev
       - libsdl2-ttf-dev
       - liblua5.3-dev
       - libglew-dev
       - libenet-dev

#before_install:
#- sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots trusty
#- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#- sudo apt-get update -qq
install:
#- sudo apt-get install -qq g++-8
#- sudo apt-get install -qq libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
#- sudo apt-get install -qq liblua5.3-dev libglew-dev
#- sudo apt-get install -qq libenet-dev
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
before_script:
- mkdir build
- cd build
- cmake ..
script: make
notifications:
  email: false
before_deploy: "zip -r duel-nightly duel6r ../resources/*"
deploy:
  provider: releases
  api_key:
    secure: eY/cYZeoK2oibIUI4yPtG3LeRgolXysnelDCEYboX21TTN2nc9SdrwtYrUlwiIdZB1WEiac1E/Ialc/h869ipM8LLSO/XOR5bJCggS8Wl9KdET+zTSHuRLwMyLaNqPP85iNlwgQQGbsd4osffH0KWuZxPDMmiVwPwyN2EjBI421MUBxuj5ln48wN7/q29NYXNF+cTEWn1/9v0JtIzmWwOWMXB1jOHDRUr50jIvdKB84MNGi14gBTB9WPD7dHFRZSbvhOIEwhM5J1pBU5XPAy4lsVHR7IrOHlxU8r3GUkqdh4isymhSPWjmwn3sIRXjXZ1s87rVM2HCrE/2S3oDmghCAyjXg6AIp5oOagUbTEu+k6WAprRn33KYNjwgKxCK8udgTjR1XRs/kpwUgXYKPYJld5jZIud260azvTnoy87PWmPlGrVgP9EYfwXKF1PrDNRr5sybHEdhBxMKFg2zyHF1QG4guBwziNvHJwHpmFftlh+3I1055f3uIsnxYEmiK4xmydMndEmoZW7Yd7G8Rh+FHQbSBN7z4nxgqI4IdxF3X4+g4p1cgPKaij31yXxV//bOPmFWc3x21gci13uzxKaWS1iW1HCo8Kv6BO4V273HhxV/wiOFLiHBVu25yo/zalpEwhIRM71OP18PIO0GLtaWmGxlREsZnd7rA7+MVXjx8=
  skip_cleanup: true
  file: "duel-nightly.zip"
  on:
    tags: true